//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETBAOCAOTON
    {
        public string MaBaoCaoTon { get; set; }
        public string MaSach { get; set; }
        public int TonDau { get; set; }
        public int PhatSinh { get; set; }
        public int TonCuoi { get; set; }
    
        public virtual BAOCAOTON BAOCAOTON { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
