//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETBAOCAOCONGNO
    {
        public string MaBaoCaoCongNo { get; set; }
        public string MaKhachHang { get; set; }
        public decimal NoDau { get; set; }
        public decimal PhatSinh { get; set; }
        public decimal NoCuoi { get; set; }
    
        public virtual BAOCAOCONGNO BAOCAOCONGNO { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
